Repository Hanhae99-final-3team/final_FE, pull requests merged in 2022-09, with the labels that each got.

#36 Feat/comment
  src/components/market/comment/Comment.jsx
  src/components/market/detail/BtnSlider.js
  src/components/market/detail/DetailInfo.jsx
  src/components/market/detail/Slider.css
  src/components/market/detail/Slider.js
  src/components/market/detail/icons/left-arrow.svg
  src/components/market/detail/icons/right-arrow.svg
  src/redux/store.js
  src/routers/Routers.jsx
Labels: enhancement, feature

#39 <feat> 카카오 공유하기 성공
  .env
  src/components/elements/buttons/KakaoSharedButton.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/detail/Share.jsx
  src/components/market/detail/SimpleSlider.jsx
Labels: enhancement, feature

#42 <feat> 로그인/회원가입 서버와 연동 성공
  .env
  src/components/register/LoginForm.jsx
  src/components/register/SignupForm.jsx
  src/redux/modules/user/userActions.js
  src/redux/modules/user/userSlice.js
Labels: documentation, feature

#45 <feat> 로그인/회원가입 디자인 수정
  public/index.html
  src/components/register/LoginForm.jsx
  src/components/register/SignupForm.jsx
Labels: documentation, feature

#47 0902 작업 완료
  .env
  public/index.html
  src/components/market/detail/DetailInfo.jsx
  src/components/market/main/Item.jsx
  src/components/register/LoginForm.jsx
  src/components/register/SignupForm.jsx
  src/redux/modules/market/postSlice.js
  src/redux/modules/user/userActions.js
  src/redux/modules/user/userSlice.js
  src/shared/axios.js
Labels: enhancement, feature

#48 <feat> 회원가입 초기화 + 아이콘 수정
  src/components/elements/header/Menu.js
  src/components/market/detail/DetailInfo.jsx
  src/components/register/SignupForm.jsx
Labels: enhancement, feature

#56 <feat> 메인페이지 필터링 구현
  src/components/market/main/ItemList.jsx
  src/components/market/main/MainContainer.jsx
  src/components/market/main/Option.js
  src/redux/modules/market/postSlice.js
Labels: enhancement, feature

#64 Feat/chart
  package.json
  src/assets/icons/account_circle.svg
  src/assets/icons/add.svg
  src/assets/icons/arrow_back_ios.svg
  src/assets/icons/chat_bubble.svg
  src/assets/icons/close.svg
  src/assets/icons/comment-1.svg
  src/assets/icons/comment.svg
  src/assets/icons/edit_document.svg
  src/assets/icons/favorite-1.svg
  src/assets/icons/favorite.svg
  src/assets/icons/home.svg
  src/assets/icons/location_searching.svg
  src/assets/icons/menu.svg
  src/assets/icons/photo_camera.svg
  src/assets/icons/profile_img_m.svg
  src/assets/icons/profile_img_sm.svg
  src/assets/icons/search.svg
  src/assets/icons/search2.svg
  src/assets/icons/send.svg
  src/assets/icons/share.svg
  src/assets/icons/visibility-1.svg
  src/assets/icons/visibility.svg
  src/assets/icons/visibility_off.svg
  src/components/elements/GlobalButton.jsx
  src/components/elements/buttons/AddPostButton.jsx
  src/components/elements/buttons/FixTwoButton.jsx
  src/components/elements/buttons/ItemZzimButton.jsx
  src/components/elements/chart/PriceChart.jsx
  src/components/elements/chart/ZzimChart.jsx
  src/components/elements/header/Menu.jsx
  src/components/market/create/Create.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/detail/SimpleSlider.jsx
  src/components/market/main/Item.jsx
  src/components/market/main/MainContainer.jsx
  src/components/market/update/Update.jsx
  src/components/user/MyPage.jsx
  src/components/user/MyPageChart.jsx
  src/components/user/MyPageContainer.jsx
  src/components/user/Profile.jsx
  src/index.js
  src/page/market/Main.jsx
  src/redux/modules/market/postSlice.js
  src/shared/axios.js
  yarn.lock
Labels: enhancement, feature

#66 <feat> Input 초기화 기능 버튼
  src/assets/icons/close.svg
  src/components/elements/buttons/InputResetButton.jsx
  src/components/market/create/Create.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/main/Item.jsx
  src/components/market/main/ItemList.jsx
  src/components/market/update/Update.jsx
  src/styles/Theme.jsx
Labels: enhancement, feature

#67 <fix> GNB 아이콘 추가, 메인페이지 CSS
  src/assets/icons/comment.svg
  src/components/elements/GlobalHeader.jsx
  src/components/market/create/Create.jsx
  src/components/market/main/Item.jsx
  src/components/market/update/Update.jsx
  src/index.css
Labels: enhancement, feature

#68 [기능 개발] PriceChart
  src/components/elements/chart/PriceChart.jsx
Labels: enhancement, feature

#71 <feat> GNB(Global Navigation Bar) 버전 2,3
  src/components/elements/GlobalHeader2.jsx
  src/components/elements/header/SearchHeader.jsx
  src/page/Search.jsx
  src/page/market/Detail.jsx
  src/page/market/Posting.jsx
  src/page/market/PostingUpdate.jsx
Labels: enhancement, feature

#72 <feat> fixbutton, fixThreeButton 개발
  src/assets/icons/check_circle.svg
  src/assets/icons/delete.svg
  src/assets/icons/edit_document2.svg
  src/components/elements/buttons/FixButton.jsx
  src/components/elements/buttons/FixThreeButton.jsx
  src/components/elements/buttons/FixTwoButton.jsx
  src/components/market/create/Create.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/update/Update.jsx
Labels: enhancement, feature

#73 <feat> 무한스크롤 구현 99퍼 성공
  src/components/elements/GlobalHeader.jsx
  src/components/elements/header/Menu.jsx
  src/components/market/main/Item.jsx
  src/components/market/main/ItemList.jsx
  src/components/market/main/MainContainer.jsx
  src/index.js
  src/page/market/Main.jsx
  src/redux/modules/market/postSlice.js
  src/shared/axios.js
Labels: enhancement, feature

#79 Feat/common design
  package.json
  src/components/elements/GlobalModal.jsx
  src/components/elements/buttons/ItemZzimButton.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/main/MainContainer.jsx
  src/components/modal/Modal.jsx
  src/components/register/LoginForm.jsx
  src/components/register/SignupForm.jsx
  src/components/register/socialLogin/KakaoLogin.jsx
  src/components/user/MyPageChart.jsx
  src/components/user/MyPageJjimContainer.jsx
  src/page/MyPageJjim.jsx
  src/page/market/Main.jsx
  src/redux/modules/user/userSlice.js
  yarn.lock
Labels: enhancement, feature

#83 [기능 개발] 차트 - 게시글 상세 / 마이페이지
  src/components/elements/chart/MyPageSumPriceChart.jsx
  src/components/elements/chart/PriceChart.jsx
  src/components/elements/chart/ZzimChart.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/user/MyPageChart.jsx
  src/redux/modules/chartSlice.js
  src/redux/modules/heartSlice.js
  src/redux/store.js
  src/shared/axios.js
Labels: enhancement, feature

#86 [기능 개발] 내가 찜한 상품 / 최근 본 상품/ 내가 쓴 글 페이지
  src/components/myPage/products/MyViewedProductsContainer.jsx
  src/components/myPage/products/MyViewedProductsItem.jsx
  src/components/myPage/products/MyViewedProductsList.jsx
  src/components/myPage/writings/MyWritingsContainer.jsx
  src/components/myPage/writings/MyWritingsItem.jsx
  src/components/myPage/writings/MyWritingsList.jsx
  src/components/myPage/zzim/MyPageZzimContainer.jsx
  src/components/myPage/zzim/MyZzimItem.jsx
  src/components/myPage/zzim/MyZzimList.jsx
  src/redux/modules/myPageSlice.js
  src/redux/store.js
  src/shared/axios.js
Labels: enhancement, feature

#87 <fix> 이전 페이지 이동 에러
  src/components/elements/GlobalHeader2.jsx
  src/components/elements/header/SearchHeader.jsx
  src/page/myPage/MyViewedProucts.jsx
  src/page/myPage/MyWritings.jsx
  src/page/myPage/MyZzim.jsx
Labels: bug

#90 <fix> 자동완성 창이 사라지지 않는 오류
  src/components/search/SearchHeader.jsx
Labels: bug

#91 [기능 개발] 쿠키 생성 및 웹 브라우저에 저장
  src/components/search/SearchHeader.jsx
  src/redux/modules/market/postSlice.js
  src/redux/modules/myPageSlice.js
  src/shared/axios.js
  src/shared/cookie.js
Labels: enhancement, feature

#92 UI/UX 디테일 수정
  src/assets/icons/comment-1.svg
  src/assets/icons/heart_zzim_list.svg
  src/components/elements/GlobalHeader.jsx
  src/components/elements/GlobalHeader2.jsx
  src/components/elements/buttons/FixButton.jsx
  src/components/elements/buttons/FixThreeButton.jsx
  src/components/elements/header/Menu.jsx
  src/components/market/create/Create.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/main/MainContainer.jsx
  src/components/market/update/Update.jsx
  src/components/myPage/MyPage.jsx
  src/components/myPage/Profile.jsx
  src/components/myPage/products/MyViewedProductsContainer.jsx
  src/components/myPage/writings/MyWritingsContainer.jsx
  src/components/myPage/zzim/MyPageZzimContainer.jsx
  src/components/myPage/zzim/MyZzimItem.jsx
  src/components/search/Search.jsx
  src/components/search/SearchHeader.jsx
  src/components/search/popular/PopularSearchList.jsx
  src/components/search/recent/RecentSearchKeyword.jsx
  src/components/searchResult/SearchResultContainer.jsx
  src/index.css
  src/page/market/Detail.jsx
  src/page/market/Main.jsx
  src/page/market/Posting.jsx
  src/page/market/PostingUpdate.jsx
  src/page/myPage/MyPage.jsx
  src/page/myPage/MyViewedProucts.jsx
  src/page/myPage/MyWritings.jsx
  src/page/myPage/MyZzim.jsx
  src/page/search/Search.jsx
  src/page/search/SearchResult.jsx
  src/redux/modules/filter/mainFilterSlice.js
  src/redux/modules/market/postSlice.js
  src/redux/modules/myPageSlice.js
  src/redux/modules/user/userActions.js
  src/shared/axios.js
  src/shared/cookie.js
Labels: bug

#94 [기능 개발] 게시글 작성 / 수정 페이지 - 이미지 슬라이더 css
  src/components/elements/GlobalImgSlider.jsx
  src/components/elements/buttons/FixButton.jsx
  src/components/market/create/Create.jsx
  src/components/market/update/Update.jsx
  src/page/market/Posting.jsx
  src/page/market/PostingUpdate.jsx
Labels: bug, documentation, enhancement

#97 <fix> PriceChart 평균 가격 색 변경
  src/components/elements/chart/PriceChart.jsx
Labels: bug

#99 <fix> 자동완성 키워드 검색 에러
  src/components/search/SearchHeader.jsx
Labels: bug

#101 <fix> 로그인 버튼 styled-component 조건부 렌더링
  src/components/elements/buttons/AddPostButton.jsx
  src/page/market/Main.jsx
Labels: bug

#103 input 타입이 number일 때 스크롤 내리면 증감되는 현상
  src/components/elements/GlobalImgSlider.jsx
  src/components/market/create/Create.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/update/Update.jsx
Labels: bug

#104 이미지 슬라이더 이슈 해결
  src/components/elements/GlobalImgSlider.jsx
  src/components/elements/buttons/FixButton.jsx
  src/components/market/create/Create.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/update/Update.jsx
Labels: bug

#108 <fix> 카카오톡 공유하기 에러
  src/components/market/detail/DetailInfo.jsx
Labels: bug

#109 최근 검색어 자동 저장 켜기 끄기 기능
  src/components/market/detail/DetailInfo.jsx
  src/components/search/Search.jsx
  src/redux/modules/searchSlice.js
  src/shared/axios.js
Labels: enhancement, feature

#111 <fix> 최근 검색어 개별 삭제가 안되는 버그
  src/redux/modules/searchSlice.js
Labels: bug

#113 토글 조건부 렌더링과 블링킹 에러 해결
  src/components/search/Search.jsx
Labels: bug

#114 GlobalAccordian 컴포넌트 구현
  src/assets/icons/add-1.svg
  src/assets/icons/remove.svg
  src/components/elements/GlobalAccordian.jsx
  src/components/market/detail/DetailInfo.jsx
Labels: enhancement, feature

#118 <feat> 최근 검색어 검색 기능 연결
  src/components/search/recent/RecentSearchKeyword.jsx
Labels: enhancement, feature

#122 <fix> 스와이퍼 간격 조정
  src/components/search/popular/PopularSearchKeyword.jsx
  src/components/search/popular/PopularSearchList.jsx
Labels: bug

#124 <fix> 마이페이지 가격 총합 차트 css 변경
  src/components/elements/chart/MyPageSumPriceChart.jsx
  src/components/myPage/MyPageChart.jsx
Labels: good first issue, feature

#126 125 검색 결과가 없습니다 페이지
  src/components/searchResult/SearchResultContainer.jsx
  src/page/myPage/MyPage.jsx
  src/page/myPage/MyViewedProucts.jsx
  src/page/myPage/MyWritings.jsx
  src/page/myPage/MyZzim.jsx
  src/page/search/SearchResult.jsx
Labels: bug

#134 127 webvital로 성능 최적화 해보기
  public/index.html
Labels: enhancement, feature

#135 132 서버 api 환경변수 처리하기
  .env
  .gitignore
  src/shared/axios.js
Labels: bug

#136 <fix> gitignore에 env파일 추가
  .gitignore
Labels: bug

#137 <fix> 카카오 map api 환경변수 설정
  src/components/market/create/Create.jsx
  src/components/market/update/Update.jsx
  src/components/myPage/Profile.jsx
Labels: enhancement, feature

#139 <fix> global header1,2, search header css 변경
  src/assets/icons/arrow_back_ios.svg
  src/assets/icons/comment.svg
  src/assets/icons/search.svg
  src/assets/icons/search2.svg
  src/components/elements/GlobalHeader.jsx
  src/components/elements/GlobalHeader2.jsx
  src/components/elements/header/Burger.jsx
  src/components/search/SearchHeader.jsx
  src/styles/Theme.jsx
Labels: enhancement, feature

#142 140 search header에 x버튼 추가
  src/components/elements/buttons/InputResetButton.jsx
  src/components/market/create/Create.jsx
  src/components/search/SearchHeader.jsx
Labels: enhancement, feature

#143 <fix> globalSelect props 추가
  src/assets/icons/arrow_drop_down.svg
  src/components/elements/GlobalSelect.jsx
Labels: enhancement, feature

#144 GlobalSelect 게시글 Create, Update에 적용 및 렌더링 오류 해결
  src/components/market/create/Create.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/options/ItemOption.js
  src/components/market/options/PetOption.js
  src/components/market/update/Update.jsx
  src/components/searchResult/SearchResultContainer.jsx
  src/redux/modules/market/postSlice.js
  src/shared/axios.js
Labels: enhancement, feature

#146 <fix> GlobalSelect 외부영역 누르면 닫히지 않는 에러
  src/components/elements/GlobalSelect.jsx
Labels: bug

#149 수정 페이지에 수정 전 이미지 슬라이드가 없는 에러 수정
  src/components/elements/GlobalImgSlider.jsx
  src/components/elements/GlobalSelect.jsx
  src/components/market/update/Update.jsx
Labels: bug

#151 <feat> 메인 배너 이미지 슬라이더 구현
  src/components/elements/GlobalImgSlider2.jsx
  src/components/elements/buttons/NextArrowButton.jsx
  src/components/elements/buttons/PrevArrowButton.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/market/main/MainBanner.jsx
  src/components/market/main/MainContainer.jsx
  src/page/market/Main.jsx
Labels: enhancement, feature

#153 <feat> 멍냥마켓 사이트 로고 및 소개글 추가
  public/index.html
  public/logo.png
Labels: enhancement, feature

#159 155 반응형으로 페이지와 UI 변경
  src/components/elements/GlobalButton.jsx
  src/components/elements/GlobalFooter.jsx
  src/components/elements/GlobalImgSlider2.jsx
  src/components/elements/buttons/AddPostButton.jsx
  src/components/elements/chart/MyPageSumPriceChart.jsx
  src/components/elements/chart/PriceChart.jsx
  src/components/elements/header/Menu.jsx
  src/components/market/detail/DetailInfo.jsx
  src/components/myPage/MyPage.jsx
  src/components/myPage/MyPageChart.jsx
  src/components/myPage/Profile.jsx
  src/components/searchResult/SearchItem.jsx
  src/components/searchResult/SearchResultContainer.jsx
  src/page/market/Main.jsx
  src/page/myPage/MyPage.jsx
  src/page/myPage/MyViewedProucts.jsx
  src/page/myPage/MyWritings.jsx
  src/page/myPage/MyZzim.jsx
  src/page/register/Login.jsx
  src/page/search/Search.jsx
  src/page/search/SearchResult.jsx
  src/styles/Theme.jsx
Labels: enhancement, feature

#164 댓글 수정 css 및 기능 구현
  src/App.js
  src/components/market/comment/Comment.jsx
  src/components/market/detail/DetailInfo.jsx
  src/redux/modules/market/commentSlice.js
Labels: enhancement, feature
